package stms.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_button", "id", Button.class);
		arp.addMapping("t_company", "id", Company.class);
		arp.addMapping("t_department", "id", Department.class);
		arp.addMapping("t_dictionary", "id", Dictionary.class);
		arp.addMapping("t_domes_in_warehouse", "id", DomesInWarehouse.class);
		arp.addMapping("t_domes_out_warehouse", "id", DomesOutWarehouse.class);
		arp.addMapping("t_domes_warehouse_fees", "id", DomesWarehouseFees.class);
		arp.addMapping("t_import_freight", "id", ImportFreight.class);
		arp.addMapping("t_import_materials", "id", ImportMaterials.class);
		arp.addMapping("t_inter_in_warehouse", "id", InterInWarehouse.class);
		arp.addMapping("t_manual_import", "id", ManualImport.class);
		arp.addMapping("t_manual_loss", "id", ManualLoss.class);
		arp.addMapping("t_manual_product", "id", ManualProduct.class);
		arp.addMapping("t_manual_sum", "id", ManualSum.class);
		arp.addMapping("t_menu", "id", Menu.class);
		arp.addMapping("t_role", "id", Role.class);
		arp.addMapping("t_role_button", "id", RoleButton.class);
		arp.addMapping("t_role_menu", "id", RoleMenu.class);
		arp.addMapping("t_standard_charge_domestic", "id", StandardChargeDomestic.class);
		arp.addMapping("t_supplier", "id", Supplier.class);
		arp.addMapping("t_supplier_contacts", "id", SupplierContacts.class);
		arp.addMapping("t_supplier_level", "id", SupplierLevel.class);
		arp.addMapping("t_supplier_month_assess", "id", SupplierMonthAssess.class);
		arp.addMapping("t_supplier_qualification", "id", SupplierQualification.class);
		arp.addMapping("t_supplier_year_assess", "id", SupplierYearAssess.class);
		arp.addMapping("t_user", "id", User.class);
		arp.addMapping("t_user_log", "id", UserLog.class);
	}
}

