package stms.model;

import stms.model.base.BaseDomesWarehouseFees;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DomesWarehouseFees extends BaseDomesWarehouseFees<DomesWarehouseFees> {
	public static final DomesWarehouseFees dao = new DomesWarehouseFees().dao();
}
