package stms.model;

import stms.model.base.BaseDomesOutWarehouse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DomesOutWarehouse extends BaseDomesOutWarehouse<DomesOutWarehouse> {
	public static final DomesOutWarehouse dao = new DomesOutWarehouse().dao();
}
