package stms.model;

import stms.model.base.BaseDomesInWarhouse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DomesInWarhouse extends BaseDomesInWarhouse<DomesInWarhouse> {
	public static final DomesInWarhouse dao = new DomesInWarhouse().dao();
}
