package stms.model;

import stms.model.base.BaseDomesInWarehouse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DomesInWarehouse extends BaseDomesInWarehouse<DomesInWarehouse> {
	public static final DomesInWarehouse dao = new DomesInWarehouse().dao();
}
