package stms.model;

import stms.model.base.BaseImportTaxBreak;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImportTaxBreak extends BaseImportTaxBreak<ImportTaxBreak> {
	public static final ImportTaxBreak dao = new ImportTaxBreak().dao();
}
