package stms.model;

import stms.model.base.BaseImportFloworder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImportFloworder extends BaseImportFloworder<ImportFloworder> {
	public static final ImportFloworder dao = new ImportFloworder().dao();
}
