package stms.model;

import stms.model.base.BaseImportTax;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImportTax extends BaseImportTax<ImportTax> {
	public static final ImportTax dao = new ImportTax().dao();
}
