package stms.model;

import stms.model.base.BaseImportMaterials;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImportMaterials extends BaseImportMaterials<ImportMaterials> {
	public static final ImportMaterials dao = new ImportMaterials().dao();
}
