package stms.model;

import stms.model.base.BaseImportDomesticTaxdetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImportDomesticTaxdetails extends BaseImportDomesticTaxdetails<ImportDomesticTaxdetails> {
	public static final ImportDomesticTaxdetails dao = new ImportDomesticTaxdetails().dao();
}
