package stms.model;

import stms.model.base.BaseImportFreight;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImportFreight extends BaseImportFreight<ImportFreight> {
	public static final ImportFreight dao = new ImportFreight().dao();
}
