package stms.model;

import stms.model.base.BaseInterWarehouseFeesOut;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InterWarehouseFeesOut extends BaseInterWarehouseFeesOut<InterWarehouseFeesOut> {
	public static final InterWarehouseFeesOut dao = new InterWarehouseFeesOut().dao();
}
