package stms.model;

import stms.model.base.BaseInterInWarehouse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InterInWarehouse extends BaseInterInWarehouse<InterInWarehouse> {
	public static final InterInWarehouse dao = new InterInWarehouse().dao();
}
