package stms.model;

import stms.model.base.BaseInterOutWarehouse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InterOutWarehouse extends BaseInterOutWarehouse<InterOutWarehouse> {
	public static final InterOutWarehouse dao = new InterOutWarehouse().dao();
}
