package stms.model;

import stms.model.base.BaseInterWarehouseFeesIn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InterWarehouseFeesIn extends BaseInterWarehouseFeesIn<InterWarehouseFeesIn> {
	public static final InterWarehouseFeesIn dao = new InterWarehouseFeesIn().dao();
}
