package stms.model;

import stms.model.base.BaseLocationComparison;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LocationComparison extends BaseLocationComparison<LocationComparison> {
	public static final LocationComparison dao = new LocationComparison().dao();
}
