package stms.model;

import stms.model.base.BaseManualProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManualProduct extends BaseManualProduct<ManualProduct> {
	public static final ManualProduct dao = new ManualProduct().dao();
}
