package stms.model;

import stms.model.base.BaseManualImport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManualImport extends BaseManualImport<ManualImport> {
	public static final ManualImport dao = new ManualImport().dao();
}
