package stms.model;


import stms.model.base.BaseManualSum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManualSum extends BaseManualSum<ManualSum> {
	public static final ManualSum dao = new ManualSum().dao(); 
}
