package stms.model;

import stms.model.base.BaseManualLoss;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManualLoss extends BaseManualLoss<ManualLoss> {
	public static final ManualLoss dao = new ManualLoss().dao();
}
