package stms.model;

import stms.model.base.BaseStandardChargeInternational;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StandardChargeInternational extends BaseStandardChargeInternational<StandardChargeInternational> {
	public static final StandardChargeInternational dao = new StandardChargeInternational().dao();
}
