package stms.model;

import stms.model.base.BaseStandardChargeDomestic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StandardChargeDomestic extends BaseStandardChargeDomestic<StandardChargeDomestic> {
	public static final StandardChargeDomestic dao = new StandardChargeDomestic().dao();
}
