package stms.model;

import stms.model.base.BaseSupplierLevel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierLevel extends BaseSupplierLevel<SupplierLevel> {
	public static final SupplierLevel dao = new SupplierLevel().dao();
}
