package stms.model;

import stms.model.base.BaseSupplierQualification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierQualification extends BaseSupplierQualification<SupplierQualification> {
	public static final SupplierQualification dao = new SupplierQualification().dao();
}
