package stms.model;

import stms.model.base.BaseSupplierMonthAssess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierMonthAssess extends BaseSupplierMonthAssess<SupplierMonthAssess> {
	public static final SupplierMonthAssess dao = new SupplierMonthAssess().dao();
}
