package stms.model;

import stms.model.base.BaseSupplierContacts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierContacts extends BaseSupplierContacts<SupplierContacts> {
	public static final SupplierContacts dao = new SupplierContacts().dao();
}
