package stms.model;

import stms.model.base.BaseSupplier;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Supplier extends BaseSupplier<Supplier> {
	public static final Supplier dao = new Supplier().dao();
}
