package stms.model;

import stms.model.base.BaseSupplierYearAssess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierYearAssess extends BaseSupplierYearAssess<SupplierYearAssess> {
	public static final SupplierYearAssess dao = new SupplierYearAssess().dao();
}
