package stms.model;

import stms.model.base.BaseTableComparison;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TableComparison extends BaseTableComparison<TableComparison> {
	public static final TableComparison dao = new TableComparison().dao();
}
