package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSupplierLevel<M extends BaseSupplierLevel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setSupplierLevel(java.lang.String supplierLevel) {
		set("supplier_level", supplierLevel);
		return (M)this;
	}

	public java.lang.String getSupplierLevel() {
		return get("supplier_level");
	}

	public M setSupplierScore(java.lang.String supplierScore) {
		set("supplier_score", supplierScore);
		return (M)this;
	}

	public java.lang.String getSupplierScore() {
		return get("supplier_score");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setReviewTime(java.util.Date reviewTime) {
		set("review_time", reviewTime);
		return (M)this;
	}

	public java.util.Date getReviewTime() {
		return get("review_time");
	}

}
