package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseManualImport<M extends BaseManualImport<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setImportNum(java.lang.String importNum) {
		set("import_num", importNum);
		return (M)this;
	}

	public java.lang.String getImportNum() {
		return get("import_num");
	}

	public M setImportRecordNum(java.lang.String importRecordNum) {
		set("import_record_num", importRecordNum);
		return (M)this;
	}

	public java.lang.String getImportRecordNum() {
		return get("import_record_num");
	}

	public M setImportCode(java.lang.String importCode) {
		set("import_code", importCode);
		return (M)this;
	}

	public java.lang.String getImportCode() {
		return get("import_code");
	}

	public M setImportName(java.lang.String importName) {
		set("import_name", importName);
		return (M)this;
	}

	public java.lang.String getImportName() {
		return get("import_name");
	}

	public M setImportSpecification(java.lang.String importSpecification) {
		set("import_specification", importSpecification);
		return (M)this;
	}

	public java.lang.String getImportSpecification() {
		return get("import_specification");
	}

	public M setMainMaterial(java.lang.String mainMaterial) {
		set("main_material", mainMaterial);
		return (M)this;
	}

	public java.lang.String getMainMaterial() {
		return get("main_material");
	}

	public M setImportUnit(java.lang.String importUnit) {
		set("import_unit", importUnit);
		return (M)this;
	}

	public java.lang.String getImportUnit() {
		return get("import_unit");
	}

	public M setImportFixedUnit(java.lang.String importFixedUnit) {
		set("import_fixed_unit", importFixedUnit);
		return (M)this;
	}

	public java.lang.String getImportFixedUnit() {
		return get("import_fixed_unit");
	}

	public M setImportReportNum(java.math.BigDecimal importReportNum) {
		set("import_report_num", importReportNum);
		return (M)this;
	}

	public java.math.BigDecimal getImportReportNum() {
		return get("import_report_num");
	}

	public M setImportReportUnitPrice(java.math.BigDecimal importReportUnitPrice) {
		set("import_report_unit_price", importReportUnitPrice);
		return (M)this;
	}

	public java.math.BigDecimal getImportReportUnitPrice() {
		return get("import_report_unit_price");
	}

	public M setImportReportTotalPrice(java.math.BigDecimal importReportTotalPrice) {
		set("import_report_total_price", importReportTotalPrice);
		return (M)this;
	}

	public java.math.BigDecimal getImportReportTotalPrice() {
		return get("import_report_total_price");
	}

	public M setCurrencySystem(java.lang.String currencySystem) {
		set("currency_system", currencySystem);
		return (M)this;
	}

	public java.lang.String getCurrencySystem() {
		return get("currency_system");
	}

	public M setImportProMarket(java.lang.String importProMarket) {
		set("import_pro_market", importProMarket);
		return (M)this;
	}

	public java.lang.String getImportProMarket() {
		return get("import_pro_market");
	}

	public M setFixedUnitRatio(java.math.BigDecimal fixedUnitRatio) {
		set("fixed_unit_ratio", fixedUnitRatio);
		return (M)this;
	}

	public java.math.BigDecimal getFixedUnitRatio() {
		return get("fixed_unit_ratio");
	}

	public M setImportLevyMode(java.lang.String importLevyMode) {
		set("import_levy_mode", importLevyMode);
		return (M)this;
	}

	public java.lang.String getImportLevyMode() {
		return get("import_levy_mode");
	}

	public M setImportHandleFlag(java.lang.String importHandleFlag) {
		set("import_handle_flag", importHandleFlag);
		return (M)this;
	}

	public java.lang.String getImportHandleFlag() {
		return get("import_handle_flag");
	}

	public M setTaxRate(java.math.BigDecimal taxRate) {
		set("tax_rate", taxRate);
		return (M)this;
	}

	public java.math.BigDecimal getTaxRate() {
		return get("tax_rate");
	}

	public M setVersion(java.lang.Integer version) {
		set("version", version);
		return (M)this;
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public M setManualId(java.lang.String manualId) {
		set("manual_id", manualId);
		return (M)this;
	}

	public java.lang.String getManualId() {
		return get("manual_id");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
