package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSupplierMonthAssess<M extends BaseSupplierMonthAssess<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setYear(java.util.Date year) {
		set("year", year);
		return (M)this;
	}

	public java.util.Date getYear() {
		return get("year");
	}

	public M setMonth(java.lang.Integer month) {
		set("month", month);
		return (M)this;
	}

	public java.lang.Integer getMonth() {
		return get("month");
	}

	public M setMonthScore(java.lang.Integer monthScore) {
		set("month_score", monthScore);
		return (M)this;
	}

	public java.lang.Integer getMonthScore() {
		return get("month_score");
	}

	public M setSupplierLevel(java.lang.String supplierLevel) {
		set("supplier_level", supplierLevel);
		return (M)this;
	}

	public java.lang.String getSupplierLevel() {
		return get("supplier_level");
	}

	public M setSupplierId(java.lang.Integer supplierId) {
		set("supplier_id", supplierId);
		return (M)this;
	}

	public java.lang.Integer getSupplierId() {
		return get("supplier_id");
	}

	public M setFile(java.lang.String file) {
		set("file", file);
		return (M)this;
	}

	public java.lang.String getFile() {
		return get("file");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setReviewTime(java.util.Date reviewTime) {
		set("review_time", reviewTime);
		return (M)this;
	}

	public java.util.Date getReviewTime() {
		return get("review_time");
	}

}
