package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseImportFloworder<M extends BaseImportFloworder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setFlowNumber(java.lang.String flowNumber) {
		set("flow_number", flowNumber);
		return (M)this;
	}

	public java.lang.String getFlowNumber() {
		return get("flow_number");
	}

	public M setIssueDate(java.util.Date issueDate) {
		set("issue_date", issueDate);
		return (M)this;
	}

	public java.util.Date getIssueDate() {
		return get("issue_date");
	}

	public M setManualId(java.lang.String manualId) {
		set("manual_id", manualId);
		return (M)this;
	}

	public java.lang.String getManualId() {
		return get("manual_id");
	}

	public M setMaterialProperties(java.lang.String materialProperties) {
		set("material_properties", materialProperties);
		return (M)this;
	}

	public java.lang.String getMaterialProperties() {
		return get("material_properties");
	}

	public M setImportSpecification(java.lang.String importSpecification) {
		set("import_specification", importSpecification);
		return (M)this;
	}

	public java.lang.String getImportSpecification() {
		return get("import_specification");
	}

	public M setImportCode(java.lang.String importCode) {
		set("import_code", importCode);
		return (M)this;
	}

	public java.lang.String getImportCode() {
		return get("import_code");
	}

	public M setBatchNum(java.lang.String batchNum) {
		set("batch_num", batchNum);
		return (M)this;
	}

	public java.lang.String getBatchNum() {
		return get("batch_num");
	}

	public M setDomesSaleNum(java.lang.Integer domesSaleNum) {
		set("domes_sale_num", domesSaleNum);
		return (M)this;
	}

	public java.lang.Integer getDomesSaleNum() {
		return get("domes_sale_num");
	}

	public M setUnit(java.lang.String unit) {
		set("unit", unit);
		return (M)this;
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public M setOverdueTaxProgress(java.lang.String overdueTaxProgress) {
		set("overdue_tax_progress", overdueTaxProgress);
		return (M)this;
	}

	public java.lang.String getOverdueTaxProgress() {
		return get("overdue_tax_progress");
	}

	public M setApplicant(java.lang.String applicant) {
		set("applicant", applicant);
		return (M)this;
	}

	public java.lang.String getApplicant() {
		return get("applicant");
	}

	public M setStorageLocation(java.lang.String storageLocation) {
		set("storage_location", storageLocation);
		return (M)this;
	}

	public java.lang.String getStorageLocation() {
		return get("storage_location");
	}

	public M setCostumBatchNum(java.lang.String costumBatchNum) {
		set("costum_batch_num", costumBatchNum);
		return (M)this;
	}

	public java.lang.String getCostumBatchNum() {
		return get("costum_batch_num");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
