package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseImportTaxBreak<M extends BaseImportTaxBreak<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setFlowNumber(java.lang.String flowNumber) {
		set("flow_number", flowNumber);
		return (M)this;
	}

	public java.lang.String getFlowNumber() {
		return get("flow_number");
	}

	public M setMaterialProperties(java.lang.String materialProperties) {
		set("material_properties", materialProperties);
		return (M)this;
	}

	public java.lang.String getMaterialProperties() {
		return get("material_properties");
	}

	public M setImportSpecification(java.lang.String importSpecification) {
		set("import_specification", importSpecification);
		return (M)this;
	}

	public java.lang.String getImportSpecification() {
		return get("import_specification");
	}

	public M setDomesSaleNum(java.lang.Integer domesSaleNum) {
		set("domes_sale_num", domesSaleNum);
		return (M)this;
	}

	public java.lang.Integer getDomesSaleNum() {
		return get("domes_sale_num");
	}

	public M setFoldPieces(java.lang.String foldPieces) {
		set("fold_pieces", foldPieces);
		return (M)this;
	}

	public java.lang.String getFoldPieces() {
		return get("fold_pieces");
	}

	public M setUnitConsume(java.math.BigDecimal unitConsume) {
		set("unit_consume", unitConsume);
		return (M)this;
	}

	public java.math.BigDecimal getUnitConsume() {
		return get("unit_consume");
	}

	public M setBondConsume(java.math.BigDecimal bondConsume) {
		set("bond_consume", bondConsume);
		return (M)this;
	}

	public java.math.BigDecimal getBondConsume() {
		return get("bond_consume");
	}

	public M setDutyPaidConsume(java.math.BigDecimal dutyPaidConsume) {
		set("duty_paid_consume", dutyPaidConsume);
		return (M)this;
	}

	public java.math.BigDecimal getDutyPaidConsume() {
		return get("duty_paid_consume");
	}

	public M setCustomBatchNum(java.lang.String customBatchNum) {
		set("custom_batch_num", customBatchNum);
		return (M)this;
	}

	public java.lang.String getCustomBatchNum() {
		return get("custom_batch_num");
	}

	public M setManualId(java.lang.String manualId) {
		set("manual_id", manualId);
		return (M)this;
	}

	public java.lang.String getManualId() {
		return get("manual_id");
	}

}
