package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDomesWarehouseFees<M extends BaseDomesWarehouseFees<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
		return (M)this;
	}

	public java.lang.String getCompanyName() {
		return get("company_name");
	}

	public M setPeriod(java.lang.String period) {
		set("period", period);
		return (M)this;
	}

	public java.lang.String getPeriod() {
		return get("period");
	}

	public M setCurrency(java.lang.String currency) {
		set("currency", currency);
		return (M)this;
	}

	public java.lang.String getCurrency() {
		return get("currency");
	}

	public M setInDate(java.util.Date inDate) {
		set("in_date", inDate);
		return (M)this;
	}

	public java.util.Date getInDate() {
		return get("in_date");
	}

	public M setInTrayQuantity(java.lang.Integer inTrayQuantity) {
		set("in_tray_quantity", inTrayQuantity);
		return (M)this;
	}

	public java.lang.Integer getInTrayQuantity() {
		return get("in_tray_quantity");
	}

	public M setUnloadingFees(java.math.BigDecimal unloadingFees) {
		set("unloading_fees", unloadingFees);
		return (M)this;
	}

	public java.math.BigDecimal getUnloadingFees() {
		return get("unloading_fees");
	}

	public M setInDrayageTypeQuantity(java.lang.String inDrayageTypeQuantity) {
		set("in_drayage_type_quantity", inDrayageTypeQuantity);
		return (M)this;
	}

	public java.lang.String getInDrayageTypeQuantity() {
		return get("in_drayage_type_quantity");
	}

	public M setInDrayage(java.math.BigDecimal inDrayage) {
		set("in_drayage", inDrayage);
		return (M)this;
	}

	public java.math.BigDecimal getInDrayage() {
		return get("in_drayage");
	}

	public M setInOvertimePay(java.math.BigDecimal inOvertimePay) {
		set("in_overtime_pay", inOvertimePay);
		return (M)this;
	}

	public java.math.BigDecimal getInOvertimePay() {
		return get("in_overtime_pay");
	}

	public M setInRemark(java.lang.String inRemark) {
		set("in_remark", inRemark);
		return (M)this;
	}

	public java.lang.String getInRemark() {
		return get("in_remark");
	}

	public M setOutDate(java.util.Date outDate) {
		set("out_date", outDate);
		return (M)this;
	}

	public java.util.Date getOutDate() {
		return get("out_date");
	}

	public M setOutTrayQuantity(java.lang.Integer outTrayQuantity) {
		set("out_tray_quantity", outTrayQuantity);
		return (M)this;
	}

	public java.lang.Integer getOutTrayQuantity() {
		return get("out_tray_quantity");
	}

	public M setLoadingFees(java.math.BigDecimal loadingFees) {
		set("loading_fees", loadingFees);
		return (M)this;
	}

	public java.math.BigDecimal getLoadingFees() {
		return get("loading_fees");
	}

	public M setOutDrayateTypeQuantity(java.lang.String outDrayateTypeQuantity) {
		set("out_drayate_type_quantity", outDrayateTypeQuantity);
		return (M)this;
	}

	public java.lang.String getOutDrayateTypeQuantity() {
		return get("out_drayate_type_quantity");
	}

	public M setOutDrayage(java.math.BigDecimal outDrayage) {
		set("out_drayage", outDrayage);
		return (M)this;
	}

	public java.math.BigDecimal getOutDrayage() {
		return get("out_drayage");
	}

	public M setOutOvertimePay(java.math.BigDecimal outOvertimePay) {
		set("out_overtime_pay", outOvertimePay);
		return (M)this;
	}

	public java.math.BigDecimal getOutOvertimePay() {
		return get("out_overtime_pay");
	}

	public M setOutRemark(java.lang.String outRemark) {
		set("out_remark", outRemark);
		return (M)this;
	}

	public java.lang.String getOutRemark() {
		return get("out_remark");
	}

	public M setWarehouseFee(java.math.BigDecimal warehouseFee) {
		set("warehouse_fee", warehouseFee);
		return (M)this;
	}

	public java.math.BigDecimal getWarehouseFee() {
		return get("warehouse_fee");
	}

}
