package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseImportTax<M extends BaseImportTax<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setImport InnerNum(java.lang.String import InnerNum) {
		set("import _inner_num", import InnerNum);
		return (M)this;
	}

	public java.lang.String getImport InnerNum() {
		return get("import _inner_num");
	}

	public M setPurchasingAgent(java.lang.String purchasingAgent) {
		set("purchasing_agent", purchasingAgent);
		return (M)this;
	}

	public java.lang.String getPurchasingAgent() {
		return get("purchasing_agent");
	}

	public M setOrderNum(java.lang.String orderNum) {
		set("order_num", orderNum);
		return (M)this;
	}

	public java.lang.String getOrderNum() {
		return get("order_num");
	}

	public M setImportName(java.lang.String importName) {
		set("import_name", importName);
		return (M)this;
	}

	public java.lang.String getImportName() {
		return get("import_name");
	}

	public M setDeclare quantity(java.lang.String declare quantity) {
		set("declare_ quantity", declare quantity);
		return (M)this;
	}

	public java.lang.String getDeclare quantity() {
		return get("declare_ quantity");
	}

	public M setDeclareUnit(java.lang.String declareUnit) {
		set("declare_unit", declareUnit);
		return (M)this;
	}

	public java.lang.String getDeclareUnit() {
		return get("declare_unit");
	}

	public M setDeclareNum(java.lang.String declareNum) {
		set("declare_num", declareNum);
		return (M)this;
	}

	public java.lang.String getDeclareNum() {
		return get("declare_num");
	}

	public M setDeclareCustoms(java.lang.String declareCustoms) {
		set("declare_customs", declareCustoms);
		return (M)this;
	}

	public java.lang.String getDeclareCustoms() {
		return get("declare_customs");
	}

	public M setTariff(java.math.BigDecimal tariff) {
		set("tariff", tariff);
		return (M)this;
	}

	public java.math.BigDecimal getTariff() {
		return get("tariff");
	}

	public M setVAT(java.math.BigDecimal VAT) {
		set("VAT", VAT);
		return (M)this;
	}

	public java.math.BigDecimal getVAT() {
		return get("VAT");
	}

	public M setTotalTax(java.math.BigDecimal totalTax) {
		set("total_tax", totalTax);
		return (M)this;
	}

	public java.math.BigDecimal getTotalTax() {
		return get("total_tax");
	}

	public M setDateApplication(java.util.Date dateApplication) {
		set("date_application", dateApplication);
		return (M)this;
	}

	public java.util.Date getDateApplication() {
		return get("date_application");
	}

	public M setReturnBillDate(java.util.Date returnBillDate) {
		set("return_bill_date", returnBillDate);
		return (M)this;
	}

	public java.util.Date getReturnBillDate() {
		return get("return_bill_date");
	}

}
