package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserLog<M extends BaseUserLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUserAccount(java.lang.String userAccount) {
		set("user_account", userAccount);
		return (M)this;
	}

	public java.lang.String getUserAccount() {
		return get("user_account");
	}

	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M)this;
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public M setAgent(java.lang.String agent) {
		set("agent", agent);
		return (M)this;
	}

	public java.lang.String getAgent() {
		return get("agent");
	}

	public M setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
		return (M)this;
	}

	public java.util.Date getLoginTime() {
		return get("login_time");
	}

	public M setLogoutTime(java.util.Date logoutTime) {
		set("logout_time", logoutTime);
		return (M)this;
	}

	public java.util.Date getLogoutTime() {
		return get("logout_time");
	}

}
