package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseImportDomesticTaxdetails<M extends BaseImportDomesticTaxdetails<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setApplicationDate(java.util.Date applicationDate) {
		set("application_date", applicationDate);
		return (M)this;
	}

	public java.util.Date getApplicationDate() {
		return get("application_date");
	}

	public M setPayDate(java.util.Date payDate) {
		set("pay_date", payDate);
		return (M)this;
	}

	public java.util.Date getPayDate() {
		return get("pay_date");
	}

	public M setManualId(java.lang.String manualId) {
		set("manual_id", manualId);
		return (M)this;
	}

	public java.lang.String getManualId() {
		return get("manual_id");
	}

	public M setMaterialProperties(java.lang.String materialProperties) {
		set("material_properties", materialProperties);
		return (M)this;
	}

	public java.lang.String getMaterialProperties() {
		return get("material_properties");
	}

	public M setImportSpecification(java.lang.String importSpecification) {
		set("import_specification", importSpecification);
		return (M)this;
	}

	public java.lang.String getImportSpecification() {
		return get("import_specification");
	}

	public M setImportNum(java.lang.Integer importNum) {
		set("import_num", importNum);
		return (M)this;
	}

	public java.lang.Integer getImportNum() {
		return get("import_num");
	}

	public M setImportCode(java.lang.String importCode) {
		set("import_code", importCode);
		return (M)this;
	}

	public java.lang.String getImportCode() {
		return get("import_code");
	}

	public M setImportMaterialName(java.lang.String importMaterialName) {
		set("import_material_name", importMaterialName);
		return (M)this;
	}

	public java.lang.String getImportMaterialName() {
		return get("import_material_name");
	}

	public M setAmount(java.lang.Integer amount) {
		set("amount", amount);
		return (M)this;
	}

	public java.lang.Integer getAmount() {
		return get("amount");
	}

	public M setUnit(java.lang.String unit) {
		set("unit", unit);
		return (M)this;
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public M setUnitPrice(java.math.BigDecimal unitPrice) {
		set("unit_price", unitPrice);
		return (M)this;
	}

	public java.math.BigDecimal getUnitPrice() {
		return get("unit_price");
	}

	public M setCurrencySystem(java.lang.String currencySystem) {
		set("currency_system", currencySystem);
		return (M)this;
	}

	public java.lang.String getCurrencySystem() {
		return get("currency_system");
	}

	public M setDollarRate(java.math.BigDecimal dollarRate) {
		set("dollar_rate", dollarRate);
		return (M)this;
	}

	public java.math.BigDecimal getDollarRate() {
		return get("dollar_rate");
	}

	public M setDomesFeesUsd(java.math.BigDecimal domesFeesUsd) {
		set("domes_fees_usd", domesFeesUsd);
		return (M)this;
	}

	public java.math.BigDecimal getDomesFeesUsd() {
		return get("domes_fees_usd");
	}

	public M setDomesFeesRmb(java.math.BigDecimal domesFeesRmb) {
		set("domes_fees_rmb", domesFeesRmb);
		return (M)this;
	}

	public java.math.BigDecimal getDomesFeesRmb() {
		return get("domes_fees_rmb");
	}

	public M setCifPrice(java.math.BigDecimal cifPrice) {
		set("CIF_price", cifPrice);
		return (M)this;
	}

	public java.math.BigDecimal getCifPrice() {
		return get("CIF_price");
	}

	public M setTaxRate(java.math.BigDecimal taxRate) {
		set("tax_rate", taxRate);
		return (M)this;
	}

	public java.math.BigDecimal getTaxRate() {
		return get("tax_rate");
	}

	public M setTariff(java.math.BigDecimal tariff) {
		set("tariff", tariff);
		return (M)this;
	}

	public java.math.BigDecimal getTariff() {
		return get("tariff");
	}

	public M setVAT(java.math.BigDecimal VAT) {
		set("VAT", VAT);
		return (M)this;
	}

	public java.math.BigDecimal getVAT() {
		return get("VAT");
	}

	public M setTaxReliefDays(java.lang.Integer taxReliefDays) {
		set("tax_relief_days", taxReliefDays);
		return (M)this;
	}

	public java.lang.Integer getTaxReliefDays() {
		return get("tax_relief_days");
	}

	public M setDeferTariff(java.math.BigDecimal deferTariff) {
		set("defer_tariff", deferTariff);
		return (M)this;
	}

	public java.math.BigDecimal getDeferTariff() {
		return get("defer_tariff");
	}

	public M setDeferVat(java.math.BigDecimal deferVat) {
		set("defer_VAT", deferVat);
		return (M)this;
	}

	public java.math.BigDecimal getDeferVat() {
		return get("defer_VAT");
	}

	public M setActualTaxTotal(java.math.BigDecimal actualTaxTotal) {
		set("actual_tax_total", actualTaxTotal);
		return (M)this;
	}

	public java.math.BigDecimal getActualTaxTotal() {
		return get("actual_tax_total");
	}

	public M setDomesTaxReportNum(java.lang.String domesTaxReportNum) {
		set("domes_tax_report_num", domesTaxReportNum);
		return (M)this;
	}

	public java.lang.String getDomesTaxReportNum() {
		return get("domes_tax_report_num");
	}

	public M setTaxProject(java.lang.String taxProject) {
		set("tax_project", taxProject);
		return (M)this;
	}

	public java.lang.String getTaxProject() {
		return get("tax_project");
	}

	public M setInnerTransferNo(java.lang.String innerTransferNo) {
		set("inner_transfer_no", innerTransferNo);
		return (M)this;
	}

	public java.lang.String getInnerTransferNo() {
		return get("inner_transfer_no");
	}

	public M setIssueDate(java.util.Date issueDate) {
		set("issue_date", issueDate);
		return (M)this;
	}

	public java.util.Date getIssueDate() {
		return get("issue_date");
	}

	public M setWithdrawalDate(java.util.Date withdrawalDate) {
		set("withdrawal_date", withdrawalDate);
		return (M)this;
	}

	public java.util.Date getWithdrawalDate() {
		return get("withdrawal_date");
	}

	public M setReceipttaxDate(java.util.Date receipttaxDate) {
		set("receipttax_date", receipttaxDate);
		return (M)this;
	}

	public java.util.Date getReceipttaxDate() {
		return get("receipttax_date");
	}

	public M setIscompletedCustomsProcedures(java.lang.String iscompletedCustomsProcedures) {
		set("iscompleted_customs_procedures", iscompletedCustomsProcedures);
		return (M)this;
	}

	public java.lang.String getIscompletedCustomsProcedures() {
		return get("iscompleted_customs_procedures");
	}

	public M setCostumBatchNum(java.lang.String costumBatchNum) {
		set("costum_batch_num", costumBatchNum);
		return (M)this;
	}

	public java.lang.String getCostumBatchNum() {
		return get("costum_batch_num");
	}

	public M setActualTaxrate(java.math.BigDecimal actualTaxrate) {
		set("actual_taxrate", actualTaxrate);
		return (M)this;
	}

	public java.math.BigDecimal getActualTaxrate() {
		return get("actual_taxrate");
	}

	public M setCustomsBroker(java.lang.String customsBroker) {
		set("customs_broker", customsBroker);
		return (M)this;
	}

	public java.lang.String getCustomsBroker() {
		return get("customs_broker");
	}

	public M setBusinessType(java.lang.String businessType) {
		set("business_type", businessType);
		return (M)this;
	}

	public java.lang.String getBusinessType() {
		return get("business_type");
	}

	public M setAngentFee(java.math.BigDecimal angentFee) {
		set("angent_fee", angentFee);
		return (M)this;
	}

	public java.math.BigDecimal getAngentFee() {
		return get("angent_fee");
	}

	public M setTransferFee(java.math.BigDecimal transferFee) {
		set("transfer_fee", transferFee);
		return (M)this;
	}

	public java.math.BigDecimal getTransferFee() {
		return get("transfer_fee");
	}

	public M setTotal(java.math.BigDecimal total) {
		set("total", total);
		return (M)this;
	}

	public java.math.BigDecimal getTotal() {
		return get("total");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
