package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInterWarehouseFeesOut<M extends BaseInterWarehouseFeesOut<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
		return (M)this;
	}

	public java.lang.String getCompanyName() {
		return get("company_name");
	}

	public M setPeriod(java.lang.String period) {
		set("period", period);
		return (M)this;
	}

	public java.lang.String getPeriod() {
		return get("period");
	}

	public M setCurrency(java.lang.String currency) {
		set("currency", currency);
		return (M)this;
	}

	public java.lang.String getCurrency() {
		return get("currency");
	}

	public M setOutDate(java.util.Date outDate) {
		set("out_date", outDate);
		return (M)this;
	}

	public java.util.Date getOutDate() {
		return get("out_date");
	}

	public M setOutContainerNo(java.lang.String outContainerNo) {
		set("out_container_no", outContainerNo);
		return (M)this;
	}

	public java.lang.String getOutContainerNo() {
		return get("out_container_no");
	}

	public M setOutTrayQuantity(java.lang.Integer outTrayQuantity) {
		set("out_tray_quantity", outTrayQuantity);
		return (M)this;
	}

	public java.lang.Integer getOutTrayQuantity() {
		return get("out_tray_quantity");
	}

	public M setLoadingFees(java.math.BigDecimal loadingFees) {
		set("loading_fees", loadingFees);
		return (M)this;
	}

	public java.math.BigDecimal getLoadingFees() {
		return get("loading_fees");
	}

	public M setCustomsFees(java.math.BigDecimal customsFees) {
		set("customs_fees", customsFees);
		return (M)this;
	}

	public java.math.BigDecimal getCustomsFees() {
		return get("customs_fees");
	}

	public M setFileFees(java.math.BigDecimal fileFees) {
		set("file_fees", fileFees);
		return (M)this;
	}

	public java.math.BigDecimal getFileFees() {
		return get("file_fees");
	}

	public M setDeliveryFees(java.math.BigDecimal deliveryFees) {
		set("delivery_fees", deliveryFees);
		return (M)this;
	}

	public java.math.BigDecimal getDeliveryFees() {
		return get("delivery_fees");
	}

	public M setOtherFees(java.math.BigDecimal otherFees) {
		set("other_fees", otherFees);
		return (M)this;
	}

	public java.math.BigDecimal getOtherFees() {
		return get("other_fees");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setInvoiceNo(java.lang.String invoiceNo) {
		set("invoice_no", invoiceNo);
		return (M)this;
	}

	public java.lang.String getInvoiceNo() {
		return get("invoice_no");
	}

	public M setDeliveryNo(java.lang.String deliveryNo) {
		set("delivery_no", deliveryNo);
		return (M)this;
	}

	public java.lang.String getDeliveryNo() {
		return get("delivery_no");
	}

}
