package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseImportMaterials<M extends BaseImportMaterials<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setImportInnerNum(java.lang.String importInnerNum) {
		set("import_inner_num", importInnerNum);
		return (M)this;
	}

	public java.lang.String getImportInnerNum() {
		return get("import_inner_num");
	}

	public M setPurchasingAgent(java.lang.String purchasingAgent) {
		set("purchasing_agent", purchasingAgent);
		return (M)this;
	}

	public java.lang.String getPurchasingAgent() {
		return get("purchasing_agent");
	}

	public M setOrderNum(java.lang.String orderNum) {
		set("order_num", orderNum);
		return (M)this;
	}

	public java.lang.String getOrderNum() {
		return get("order_num");
	}

	public M setImportInvoiceNum(java.lang.String importInvoiceNum) {
		set("import_invoice_num", importInvoiceNum);
		return (M)this;
	}

	public java.lang.String getImportInvoiceNum() {
		return get("import_invoice_num");
	}

	public M setImportName(java.lang.String importName) {
		set("import_name", importName);
		return (M)this;
	}

	public java.lang.String getImportName() {
		return get("import_name");
	}

	public M setImportSpecification(java.lang.String importSpecification) {
		set("import_specification", importSpecification);
		return (M)this;
	}

	public java.lang.String getImportSpecification() {
		return get("import_specification");
	}

	public M setImportType(java.lang.String importType) {
		set("import_type", importType);
		return (M)this;
	}

	public java.lang.String getImportType() {
		return get("import_type");
	}

	public M setDeclareQuantity(java.math.BigDecimal declareQuantity) {
		set("declare_quantity", declareQuantity);
		return (M)this;
	}

	public java.math.BigDecimal getDeclareQuantity() {
		return get("declare_quantity");
	}

	public M setDeclareUnit(java.lang.String declareUnit) {
		set("declare_unit", declareUnit);
		return (M)this;
	}

	public java.lang.String getDeclareUnit() {
		return get("declare_unit");
	}

	public M setDeclareUnitPrice(java.math.BigDecimal declareUnitPrice) {
		set("declare_unit_price", declareUnitPrice);
		return (M)this;
	}

	public java.math.BigDecimal getDeclareUnitPrice() {
		return get("declare_unit_price");
	}

	public M setImportTotalPrice(java.math.BigDecimal importTotalPrice) {
		set("import_total_price", importTotalPrice);
		return (M)this;
	}

	public java.math.BigDecimal getImportTotalPrice() {
		return get("import_total_price");
	}

	public M setCurrencySystem(java.lang.String currencySystem) {
		set("currency_system", currencySystem);
		return (M)this;
	}

	public java.lang.String getCurrencySystem() {
		return get("currency_system");
	}

	public M setImportTotalDollar(java.math.BigDecimal importTotalDollar) {
		set("import_total_dollar", importTotalDollar);
		return (M)this;
	}

	public java.math.BigDecimal getImportTotalDollar() {
		return get("import_total_dollar");
	}

	public M setImportNum(java.lang.Integer importNum) {
		set("import_num", importNum);
		return (M)this;
	}

	public java.lang.Integer getImportNum() {
		return get("import_num");
	}

	public M setPackingType(java.lang.String packingType) {
		set("packing_type", packingType);
		return (M)this;
	}

	public java.lang.String getPackingType() {
		return get("packing_type");
	}

	public M setGrossWeight(java.math.BigDecimal grossWeight) {
		set("gross_weight", grossWeight);
		return (M)this;
	}

	public java.math.BigDecimal getGrossWeight() {
		return get("gross_weight");
	}

	public M setNetWeight(java.math.BigDecimal netWeight) {
		set("net_weight", netWeight);
		return (M)this;
	}

	public java.math.BigDecimal getNetWeight() {
		return get("net_weight");
	}

	public M setSupplier(java.lang.String supplier) {
		set("supplier", supplier);
		return (M)this;
	}

	public java.lang.String getSupplier() {
		return get("supplier");
	}

	public M setTransfProperty(java.util.Date transfProperty) {
		set("transf_property", transfProperty);
		return (M)this;
	}

	public java.util.Date getTransfProperty() {
		return get("transf_property");
	}

	public M setImportDate(java.util.Date importDate) {
		set("import_date", importDate);
		return (M)this;
	}

	public java.util.Date getImportDate() {
		return get("import_date");
	}

	public M setExpectArrivalDate(java.util.Date expectArrivalDate) {
		set("expect_arrival_date", expectArrivalDate);
		return (M)this;
	}

	public java.util.Date getExpectArrivalDate() {
		return get("expect_arrival_date");
	}

	public M setActualArrivalDate(java.util.Date actualArrivalDate) {
		set("actual_arrival_date", actualArrivalDate);
		return (M)this;
	}

	public java.util.Date getActualArrivalDate() {
		return get("actual_arrival_date");
	}

	public M setImportCode(java.lang.String importCode) {
		set("import_code", importCode);
		return (M)this;
	}

	public java.lang.String getImportCode() {
		return get("import_code");
	}

	public M setDeclareNum(java.lang.String declareNum) {
		set("declare_num", declareNum);
		return (M)this;
	}

	public java.lang.String getDeclareNum() {
		return get("declare_num");
	}

	public M setMainNoteNum(java.lang.String mainNoteNum) {
		set("main_note_num", mainNoteNum);
		return (M)this;
	}

	public java.lang.String getMainNoteNum() {
		return get("main_note_num");
	}

	public M setTradeTerms(java.lang.String tradeTerms) {
		set("trade_terms", tradeTerms);
		return (M)this;
	}

	public java.lang.String getTradeTerms() {
		return get("trade_terms");
	}

	public M setTransportMode(java.lang.String transportMode) {
		set("transport_mode", transportMode);
		return (M)this;
	}

	public java.lang.String getTransportMode() {
		return get("transport_mode");
	}

	public M setDeparturePlace(java.lang.String departurePlace) {
		set("departure_place", departurePlace);
		return (M)this;
	}

	public java.lang.String getDeparturePlace() {
		return get("departure_place");
	}

	public M setLoadingPort(java.lang.String loadingPort) {
		set("loading_port", loadingPort);
		return (M)this;
	}

	public java.lang.String getLoadingPort() {
		return get("loading_port");
	}

	public M setOriginCountry(java.lang.String originCountry) {
		set("origin_country", originCountry);
		return (M)this;
	}

	public java.lang.String getOriginCountry() {
		return get("origin_country");
	}

	public M setLogisticsId(java.lang.Integer logisticsId) {
		set("logistics_id", logisticsId);
		return (M)this;
	}

	public java.lang.Integer getLogisticsId() {
		return get("logistics_id");
	}

	public M setDeclareCustoms(java.lang.String declareCustoms) {
		set("declare_customs", declareCustoms);
		return (M)this;
	}

	public java.lang.String getDeclareCustoms() {
		return get("declare_customs");
	}

	public M setTradeType(java.lang.String tradeType) {
		set("trade_type", tradeType);
		return (M)this;
	}

	public java.lang.String getTradeType() {
		return get("trade_type");
	}

	public M setManualId(java.lang.String manualId) {
		set("manual_id", manualId);
		return (M)this;
	}

	public java.lang.String getManualId() {
		return get("manual_id");
	}

	public M setItemNo(java.lang.String itemNo) {
		set("item_no", itemNo);
		return (M)this;
	}

	public java.lang.String getItemNo() {
		return get("item_no");
	}

	public M setTariff(java.math.BigDecimal tariff) {
		set("tariff", tariff);
		return (M)this;
	}

	public java.math.BigDecimal getTariff() {
		return get("tariff");
	}

	public M setVAT(java.math.BigDecimal VAT) {
		set("VAT", VAT);
		return (M)this;
	}

	public java.math.BigDecimal getVAT() {
		return get("VAT");
	}

	public M setTotalTax(java.math.BigDecimal totalTax) {
		set("Total_tax", totalTax);
		return (M)this;
	}

	public java.math.BigDecimal getTotalTax() {
		return get("Total_tax");
	}

	public M setMargin(java.math.BigDecimal margin) {
		set("margin", margin);
		return (M)this;
	}

	public java.math.BigDecimal getMargin() {
		return get("margin");
	}

	public M setPaymentDate(java.util.Date paymentDate) {
		set("payment_date", paymentDate);
		return (M)this;
	}

	public java.util.Date getPaymentDate() {
		return get("payment_date");
	}

	public M setReturnInvoiceDate(java.util.Date returnInvoiceDate) {
		set("return_invoice_date", returnInvoiceDate);
		return (M)this;
	}

	public java.util.Date getReturnInvoiceDate() {
		return get("return_invoice_date");
	}

	public M setReturnDeclareDate(java.util.Date returnDeclareDate) {
		set("return_declare_date", returnDeclareDate);
		return (M)this;
	}

	public java.util.Date getReturnDeclareDate() {
		return get("return_declare_date");
	}

	public M setReceiptNo(java.lang.String receiptNo) {
		set("receipt_no", receiptNo);
		return (M)this;
	}

	public java.lang.String getReceiptNo() {
		return get("receipt_no");
	}

	public M setReceiptType(java.lang.String receiptType) {
		set("receipt_type", receiptType);
		return (M)this;
	}

	public java.lang.String getReceiptType() {
		return get("receipt_type");
	}

}
