package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTableComparison<M extends BaseTableComparison<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setDate(java.lang.String date) {
		set("date", date);
		return (M)this;
	}

	public java.lang.String getDate() {
		return get("date");
	}

	public M setLocation1(java.lang.String location1) {
		set("location1", location1);
		return (M)this;
	}

	public java.lang.String getLocation1() {
		return get("location1");
	}

	public M setCompanyName1(java.lang.String companyName1) {
		set("company_name1", companyName1);
		return (M)this;
	}

	public java.lang.String getCompanyName1() {
		return get("company_name1");
	}

	public M setQuantity1(java.lang.Integer quantity1) {
		set("quantity1", quantity1);
		return (M)this;
	}

	public java.lang.Integer getQuantity1() {
		return get("quantity1");
	}

	public M setTrayQuantity1(java.lang.Integer trayQuantity1) {
		set("tray_quantity1", trayQuantity1);
		return (M)this;
	}

	public java.lang.Integer getTrayQuantity1() {
		return get("tray_quantity1");
	}

	public M setMaterialNo1(java.lang.String materialNo1) {
		set("material_no1", materialNo1);
		return (M)this;
	}

	public java.lang.String getMaterialNo1() {
		return get("material_no1");
	}

	public M setMaterial1(java.lang.String material1) {
		set("material1", material1);
		return (M)this;
	}

	public java.lang.String getMaterial1() {
		return get("material1");
	}

	public M setBatchNo1(java.lang.String batchNo1) {
		set("batch_no1", batchNo1);
		return (M)this;
	}

	public java.lang.String getBatchNo1() {
		return get("batch_no1");
	}

	public M setTrayNo1(java.lang.String trayNo1) {
		set("tray_no1", trayNo1);
		return (M)this;
	}

	public java.lang.String getTrayNo1() {
		return get("tray_no1");
	}

	public M setModulePower1(java.lang.Integer modulePower1) {
		set("module_power1", modulePower1);
		return (M)this;
	}

	public java.lang.Integer getModulePower1() {
		return get("module_power1");
	}

	public M setLocation2(java.lang.String location2) {
		set("location2", location2);
		return (M)this;
	}

	public java.lang.String getLocation2() {
		return get("location2");
	}

	public M setQuantity2(java.lang.Integer quantity2) {
		set("quantity2", quantity2);
		return (M)this;
	}

	public java.lang.Integer getQuantity2() {
		return get("quantity2");
	}

	public M setMaterialNo2(java.lang.String materialNo2) {
		set("material_no2", materialNo2);
		return (M)this;
	}

	public java.lang.String getMaterialNo2() {
		return get("material_no2");
	}

	public M setMaterial2(java.lang.String material2) {
		set("material2", material2);
		return (M)this;
	}

	public java.lang.String getMaterial2() {
		return get("material2");
	}

	public M setBatchNo2(java.lang.String batchNo2) {
		set("batch_no2", batchNo2);
		return (M)this;
	}

	public java.lang.String getBatchNo2() {
		return get("batch_no2");
	}

	public M setModulePower2(java.lang.Integer modulePower2) {
		set("module_power2", modulePower2);
		return (M)this;
	}

	public java.lang.Integer getModulePower2() {
		return get("module_power2");
	}

	public M setCompanyName3(java.lang.String companyName3) {
		set("company_name3", companyName3);
		return (M)this;
	}

	public java.lang.String getCompanyName3() {
		return get("company_name3");
	}

	public M setDate3(java.util.Date date3) {
		set("date3", date3);
		return (M)this;
	}

	public java.util.Date getDate3() {
		return get("date3");
	}

	public M setTrayQuantity3(java.lang.Integer trayQuantity3) {
		set("tray_quantity3", trayQuantity3);
		return (M)this;
	}

	public java.lang.Integer getTrayQuantity3() {
		return get("tray_quantity3");
	}

}
