package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInterInWarehouse<M extends BaseInterInWarehouse<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setInContainerNo(java.lang.String inContainerNo) {
		set("in_container_no", inContainerNo);
		return (M)this;
	}

	public java.lang.String getInContainerNo() {
		return get("in_container_no");
	}

	public M setInDate(java.util.Date inDate) {
		set("in_date", inDate);
		return (M)this;
	}

	public java.util.Date getInDate() {
		return get("in_date");
	}

	public M setInStorageLocation(java.lang.String inStorageLocation) {
		set("in_storage_location", inStorageLocation);
		return (M)this;
	}

	public java.lang.String getInStorageLocation() {
		return get("in_storage_location");
	}

	public M setInCompanyName(java.lang.String inCompanyName) {
		set("in_company_name", inCompanyName);
		return (M)this;
	}

	public java.lang.String getInCompanyName() {
		return get("in_company_name");
	}

	public M setInMaterialNo(java.lang.String inMaterialNo) {
		set("in_material_no", inMaterialNo);
		return (M)this;
	}

	public java.lang.String getInMaterialNo() {
		return get("in_material_no");
	}

	public M setInMaterial(java.lang.String inMaterial) {
		set("in_material", inMaterial);
		return (M)this;
	}

	public java.lang.String getInMaterial() {
		return get("in_material");
	}

	public M setInBatchNo(java.lang.String inBatchNo) {
		set("in_batch_no", inBatchNo);
		return (M)this;
	}

	public java.lang.String getInBatchNo() {
		return get("in_batch_no");
	}

	public M setInTrayNo(java.lang.String inTrayNo) {
		set("in_tray_no", inTrayNo);
		return (M)this;
	}

	public java.lang.String getInTrayNo() {
		return get("in_tray_no");
	}

	public M setInQuantity(java.lang.Integer inQuantity) {
		set("in_quantity", inQuantity);
		return (M)this;
	}

	public java.lang.Integer getInQuantity() {
		return get("in_quantity");
	}

	public M setInTrayQuantity(java.lang.Integer inTrayQuantity) {
		set("in_tray_quantity", inTrayQuantity);
		return (M)this;
	}

	public java.lang.Integer getInTrayQuantity() {
		return get("in_tray_quantity");
	}

	public M setInModulePower(java.lang.Integer inModulePower) {
		set("in_module_power", inModulePower);
		return (M)this;
	}

	public java.lang.Integer getInModulePower() {
		return get("in_module_power");
	}

}
