package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseManualLoss<M extends BaseManualLoss<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setProductNo(java.lang.Integer productNo) {
		set("product_no", productNo);
		return (M)this;
	}

	public java.lang.Integer getProductNo() {
		return get("product_no");
	}

	public M setProductName(java.lang.String productName) {
		set("product_name", productName);
		return (M)this;
	}

	public java.lang.String getProductName() {
		return get("product_name");
	}

	public M setProductSpecification(java.lang.String productSpecification) {
		set("product_specification", productSpecification);
		return (M)this;
	}

	public java.lang.String getProductSpecification() {
		return get("product_specification");
	}

	public M setProductMeasurementUnit(java.lang.String productMeasurementUnit) {
		set("product_measurement_unit", productMeasurementUnit);
		return (M)this;
	}

	public java.lang.String getProductMeasurementUnit() {
		return get("product_measurement_unit");
	}

	public M setMaterialsNo(java.lang.Integer materialsNo) {
		set("materials_no", materialsNo);
		return (M)this;
	}

	public java.lang.Integer getMaterialsNo() {
		return get("materials_no");
	}

	public M setMaterialsName(java.lang.String materialsName) {
		set("materials_name", materialsName);
		return (M)this;
	}

	public java.lang.String getMaterialsName() {
		return get("materials_name");
	}

	public M setMaterialsSpecification(java.lang.String materialsSpecification) {
		set("materials_specification", materialsSpecification);
		return (M)this;
	}

	public java.lang.String getMaterialsSpecification() {
		return get("materials_specification");
	}

	public M setMaterialsMeasurementUnit(java.lang.String materialsMeasurementUnit) {
		set("materials_measurement_unit", materialsMeasurementUnit);
		return (M)this;
	}

	public java.lang.String getMaterialsMeasurementUnit() {
		return get("materials_measurement_unit");
	}

	public M setUnitLoss(java.math.BigDecimal unitLoss) {
		set("unit_loss", unitLoss);
		return (M)this;
	}

	public java.math.BigDecimal getUnitLoss() {
		return get("unit_loss");
	}

	public M setLossRate(java.math.BigDecimal lossRate) {
		set("loss_rate", lossRate);
		return (M)this;
	}

	public java.math.BigDecimal getLossRate() {
		return get("loss_rate");
	}

	public M setLossHandleFlag(java.lang.String lossHandleFlag) {
		set("loss_handle_flag", lossHandleFlag);
		return (M)this;
	}

	public java.lang.String getLossHandleFlag() {
		return get("loss_handle_flag");
	}

	public M setUnbondMaterialRate(java.math.BigDecimal unbondMaterialRate) {
		set("unbond_material_rate", unbondMaterialRate);
		return (M)this;
	}

	public java.math.BigDecimal getUnbondMaterialRate() {
		return get("unbond_material_rate");
	}

	public M setVersion(java.lang.String version) {
		set("version", version);
		return (M)this;
	}

	public java.lang.String getVersion() {
		return get("version");
	}

	public M setManualNo(java.lang.String manualNo) {
		set("manual_no", manualNo);
		return (M)this;
	}

	public java.lang.String getManualNo() {
		return get("manual_no");
	}

	public M setCustomsDepartment(java.lang.String customsDepartment) {
		set("customs_department", customsDepartment);
		return (M)this;
	}

	public java.lang.String getCustomsDepartment() {
		return get("customs_department");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setReviewTime(java.util.Date reviewTime) {
		set("review_time", reviewTime);
		return (M)this;
	}

	public java.util.Date getReviewTime() {
		return get("review_time");
	}

}
