package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInterWarehouseFeesIn<M extends BaseInterWarehouseFeesIn<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
		return (M)this;
	}

	public java.lang.String getCompanyName() {
		return get("company_name");
	}

	public M setPeriod(java.lang.String period) {
		set("period", period);
		return (M)this;
	}

	public java.lang.String getPeriod() {
		return get("period");
	}

	public M setCurrency(java.lang.String currency) {
		set("currency", currency);
		return (M)this;
	}

	public java.lang.String getCurrency() {
		return get("currency");
	}

	public M setInDate(java.util.Date inDate) {
		set("in_date", inDate);
		return (M)this;
	}

	public java.util.Date getInDate() {
		return get("in_date");
	}

	public M setInContainerNo(java.lang.String inContainerNo) {
		set("in_container_no", inContainerNo);
		return (M)this;
	}

	public java.lang.String getInContainerNo() {
		return get("in_container_no");
	}

	public M setInTrayQuantity(java.lang.Integer inTrayQuantity) {
		set("in_tray_quantity", inTrayQuantity);
		return (M)this;
	}

	public java.lang.Integer getInTrayQuantity() {
		return get("in_tray_quantity");
	}

	public M setInHandlingFees(java.math.BigDecimal inHandlingFees) {
		set("in_handling_fees", inHandlingFees);
		return (M)this;
	}

	public java.math.BigDecimal getInHandlingFees() {
		return get("in_handling_fees");
	}

	public M setShipFees(java.math.BigDecimal shipFees) {
		set("ship_fees", shipFees);
		return (M)this;
	}

	public java.math.BigDecimal getShipFees() {
		return get("ship_fees");
	}

	public M setWarehouseFee(java.math.BigDecimal warehouseFee) {
		set("warehouse_fee", warehouseFee);
		return (M)this;
	}

	public java.math.BigDecimal getWarehouseFee() {
		return get("warehouse_fee");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
