package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseImportFreight<M extends BaseImportFreight<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setImportInvoiceNum(java.lang.String importInvoiceNum) {
		set("import_invoice_num", importInvoiceNum);
		return (M)this;
	}

	public java.lang.String getImportInvoiceNum() {
		return get("import_invoice_num");
	}

	public M setImportName(java.lang.String importName) {
		set("import_name", importName);
		return (M)this;
	}

	public java.lang.String getImportName() {
		return get("import_name");
	}

	public M setTradeTerms(java.lang.String tradeTerms) {
		set("trade_terms", tradeTerms);
		return (M)this;
	}

	public java.lang.String getTradeTerms() {
		return get("trade_terms");
	}

	public M setDeliveryNum(java.lang.String deliveryNum) {
		set("delivery_num", deliveryNum);
		return (M)this;
	}

	public java.lang.String getDeliveryNum() {
		return get("delivery_num");
	}

	public M setImportNum(java.lang.Integer importNum) {
		set("import_num", importNum);
		return (M)this;
	}

	public java.lang.Integer getImportNum() {
		return get("import_num");
	}

	public M setGrossWeight(java.math.BigDecimal grossWeight) {
		set("gross_weight", grossWeight);
		return (M)this;
	}

	public java.math.BigDecimal getGrossWeight() {
		return get("gross_weight");
	}

	public M setCustomsFees(java.math.BigDecimal customsFees) {
		set("customs_fees", customsFees);
		return (M)this;
	}

	public java.math.BigDecimal getCustomsFees() {
		return get("customs_fees");
	}

	public M setCiqBrokerageFee(java.math.BigDecimal ciqBrokerageFee) {
		set("CIQ_Brokerage_Fee", ciqBrokerageFee);
		return (M)this;
	}

	public java.math.BigDecimal getCiqBrokerageFee() {
		return get("CIQ_Brokerage_Fee");
	}

	public M setCustomsAgentFee(java.math.BigDecimal customsAgentFee) {
		set("customs_agent_fee", customsAgentFee);
		return (M)this;
	}

	public java.math.BigDecimal getCustomsAgentFee() {
		return get("customs_agent_fee");
	}

	public M setReplacementFee(java.math.BigDecimal replacementFee) {
		set("replacement_fee", replacementFee);
		return (M)this;
	}

	public java.math.BigDecimal getReplacementFee() {
		return get("replacement_fee");
	}

	public M setInspectionFee(java.math.BigDecimal inspectionFee) {
		set("inspection_fee", inspectionFee);
		return (M)this;
	}

	public java.math.BigDecimal getInspectionFee() {
		return get("inspection_fee");
	}

	public M setCustomInspectFees(java.math.BigDecimal customInspectFees) {
		set("custom_inspect_fees", customInspectFees);
		return (M)this;
	}

	public java.math.BigDecimal getCustomInspectFees() {
		return get("custom_inspect_fees");
	}

	public M setDomesticLandFreight(java.math.BigDecimal domesticLandFreight) {
		set("domestic_land_freight", domesticLandFreight);
		return (M)this;
	}

	public java.math.BigDecimal getDomesticLandFreight() {
		return get("domestic_land_freight");
	}

	public M setIncidentalFee(java.math.BigDecimal incidentalFee) {
		set("incidental_fee", incidentalFee);
		return (M)this;
	}

	public java.math.BigDecimal getIncidentalFee() {
		return get("incidental_fee");
	}

	public M setPackingInspectionFee(java.math.BigDecimal packingInspectionFee) {
		set("packing_inspection_fee", packingInspectionFee);
		return (M)this;
	}

	public java.math.BigDecimal getPackingInspectionFee() {
		return get("packing_inspection_fee");
	}

	public M setInspectionServiceFee(java.math.BigDecimal inspectionServiceFee) {
		set("inspection_service_fee", inspectionServiceFee);
		return (M)this;
	}

	public java.math.BigDecimal getInspectionServiceFee() {
		return get("inspection_service_fee");
	}

	public M setCustomsServiceCharge(java.math.BigDecimal customsServiceCharge) {
		set("customs_service_charge", customsServiceCharge);
		return (M)this;
	}

	public java.math.BigDecimal getCustomsServiceCharge() {
		return get("customs_service_charge");
	}

	public M setPickUpCharge(java.math.BigDecimal pickUpCharge) {
		set("pick_up_charge", pickUpCharge);
		return (M)this;
	}

	public java.math.BigDecimal getPickUpCharge() {
		return get("pick_up_charge");
	}

	public M setAccreditationFee(java.math.BigDecimal accreditationFee) {
		set("accreditation_fee", accreditationFee);
		return (M)this;
	}

	public java.math.BigDecimal getAccreditationFee() {
		return get("accreditation_fee");
	}

	public M setInternationalShipping(java.math.BigDecimal internationalShipping) {
		set("international_shipping", internationalShipping);
		return (M)this;
	}

	public java.math.BigDecimal getInternationalShipping() {
		return get("international_shipping");
	}

	public M setInternationalFees(java.math.BigDecimal internationalFees) {
		set("international_fees", internationalFees);
		return (M)this;
	}

	public java.math.BigDecimal getInternationalFees() {
		return get("international_fees");
	}

	public M setInternationalAgencyFee(java.math.BigDecimal internationalAgencyFee) {
		set("international_agency_fee", internationalAgencyFee);
		return (M)this;
	}

	public java.math.BigDecimal getInternationalAgencyFee() {
		return get("international_agency_fee");
	}

	public M setTotalClearcustomsRmb(java.math.BigDecimal totalClearcustomsRmb) {
		set("total_clearcustoms_rmb", totalClearcustomsRmb);
		return (M)this;
	}

	public java.math.BigDecimal getTotalClearcustomsRmb() {
		return get("total_clearcustoms_rmb");
	}

	public M setTotalClearcustomsUsd(java.math.BigDecimal totalClearcustomsUsd) {
		set("total_clearcustoms_usd", totalClearcustomsUsd);
		return (M)this;
	}

	public java.math.BigDecimal getTotalClearcustomsUsd() {
		return get("total_clearcustoms_usd");
	}

	public M setStatementDate(java.util.Date statementDate) {
		set("statement_date", statementDate);
		return (M)this;
	}

	public java.util.Date getStatementDate() {
		return get("statement_date");
	}

	public M setCostType(java.lang.String costType) {
		set("cost_type", costType);
		return (M)this;
	}

	public java.lang.String getCostType() {
		return get("cost_type");
	}

	public M setFreightPayTerms(java.lang.String freightPayTerms) {
		set("freight_pay_terms", freightPayTerms);
		return (M)this;
	}

	public java.lang.String getFreightPayTerms() {
		return get("freight_pay_terms");
	}

	public M setImportInnerNum(java.lang.String importInnerNum) {
		set("import_inner_num", importInnerNum);
		return (M)this;
	}

	public java.lang.String getImportInnerNum() {
		return get("import_inner_num");
	}

	public M setLogisticsId(java.lang.Integer logisticsId) {
		set("logistics_id", logisticsId);
		return (M)this;
	}

	public java.lang.Integer getLogisticsId() {
		return get("logistics_id");
	}

	public M setIbmsNum(java.lang.String ibmsNum) {
		set("IBMS_num", ibmsNum);
		return (M)this;
	}

	public java.lang.String getIbmsNum() {
		return get("IBMS_num");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
