package stms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDomesInWarhouse<M extends BaseDomesInWarhouse<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}

	public java.util.Date getDate() {
		return get("date");
	}

	public M setStorageLocation(java.lang.String storageLocation) {
		set("storage_location", storageLocation);
		return (M)this;
	}

	public java.lang.String getStorageLocation() {
		return get("storage_location");
	}

	public M setSupplierId(java.lang.Integer supplierId) {
		set("supplier_id", supplierId);
		return (M)this;
	}

	public java.lang.Integer getSupplierId() {
		return get("supplier_id");
	}

	public M setMaterialNo(java.lang.String materialNo) {
		set("material_no", materialNo);
		return (M)this;
	}

	public java.lang.String getMaterialNo() {
		return get("material_no");
	}

	public M setMaterial(java.lang.String material) {
		set("material", material);
		return (M)this;
	}

	public java.lang.String getMaterial() {
		return get("material");
	}

	public M setBatchNo(java.lang.String batchNo) {
		set("batch_no", batchNo);
		return (M)this;
	}

	public java.lang.String getBatchNo() {
		return get("batch_no");
	}

	public M setTrayNo(java.lang.String trayNo) {
		set("tray_no", trayNo);
		return (M)this;
	}

	public java.lang.String getTrayNo() {
		return get("tray_no");
	}

	public M setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
		return (M)this;
	}

	public java.lang.Integer getQuantity() {
		return get("quantity");
	}

	public M setTrayQuantity(java.lang.Integer trayQuantity) {
		set("tray_quantity", trayQuantity);
		return (M)this;
	}

	public java.lang.Integer getTrayQuantity() {
		return get("tray_quantity");
	}

	public M setModulePower(java.math.BigDecimal modulePower) {
		set("module_power", modulePower);
		return (M)this;
	}

	public java.math.BigDecimal getModulePower() {
		return get("module_power");
	}

}
